spec:
  template:
    spec:
      volumes:
        - name: kubegres-website-dev-putput-pv
          hostPath:
            path: /usr/share/dev-output/static-websites/kubegres-website/image
            type: DirectoryOrCreate

      containers:
        - image: localhost:5000/reactivetechio/kubegres-website:latest
          name: kubegres-website

          volumeMounts:
            - name: kubegres-website-dev-putput-pv
              mountPath: /usr/share/nginx/html
